import Head from 'next/head';
import React from 'react';

const Terms = () => {
  return (
    <>
      <Head>
        <title>The Terms and Conditions - Virtual X</title>
      </Head>
      <header className='flex justify-center py-16 bg-dark'>
        <div className='my-auto'>
          <h1 className='gradient-text text-4xl md:text-5xl'>The Terms and Conditions</h1>
          <p className='text-xs md:text-sm text-dark2 text-center'>Last updated on 22 Sep, 2023</p>
        </div>
      </header>

      <main className='mx-auto max-w-[1100px] pb-40 text-justify'>
        {/* point 1 */}
        <div className='terms-container md:mx-8 xl:mx-0'>
          <h2>Introduction</h2>
          <p>The Terms and Conditions (the “T&C” or “Terms”) apply to the buyer of the VRL Token (hereinafter “VRL TOKEN”) and future user of the VirtualX network and constitute an agreement between VirtualX and you. Please read these terms carefully before moving onto the token presale and sale. The T&C affect your obligations and legal rights, including, but not limited to, waiver of rights and limitation of liability. If you do not agree to these terms of sale, do not participate in the sale of the Tokens. By purchasing the VRL TOKENS during the token seed-funding; presale (Pre-ITO) and crowd sale period (hereinafter the “Token Sale”), you will be bound by this T&C, and all terms incorporated by reference. Your purchase of VRL TOKEN is subject to this T&C.</p>

          <p>You may not use our website, services, networks, and acquire VRL TOKENS, if you are under 18 years old, and if you are a citizen, resident, habitant or legal entity incorporated in Restricted Use Areas as described below. </p>
          <h2 className='mt-8'>Applicability: </h2>
          <ol className='list-decimal text-white ml-2 md:ml-0'>
            <li>By using our services, you are agreeing to be bound by the T&C in its latest version. You are aware that VirtualX may change this T&C at any time, on our sole discretion without any prior notice to you. Any changes will be effective immediately upon posting on our Website. Your continued use of the VirtualX Network means that you accept any new or modified terms</li>
            <li>Based on the Binance Chain, VRL will be issued as payment of services on the network, and a rewarding program for the community.</li>
            <li>Verified KYC enables clients to participate/contribute in the VRL Token sale. </li>
            <li>Virtual X does not have the legal qualification as a security, since it does not give any rights on dividends or interest, any ownership right or stake share or equivalent rights or any right to receive future revenue shares, or any other form of participation in or relating to the Company, nor shall VirtualX holders have any influence or rights in the development or governance of the Company. VRL, therefore, is not a share and does not give any right to participate in the general meetings of the Company. VRL  Token is final and non-refundable. The acquirement and use of VRL  Token shall not be done for speculative usage. </li>
            <li>VRL Token can be purchased during the Token PreSale and Sale directly from the Company or after the Token Sale at the Company or as per Company future recommendations.</li>
            <li>Company gives no warranties that VRL Tokens will be exchangeable on specific networks or that they shall remain exchangeable on exchange networks or that they would be exchangeable on other exchanges. </li>
            <li>VRL Token is not an investment advice, a security nor an investment product and any action, notice, communication, message, decision, managerial act, or omission of the mentioned shall not be understood and interpreted as such. Company gives no guarantees as to the value of any of the VRL Tokens and explicitly warns users that there is no reason to believe that VRL Token will increase in value, and they might also decrease in value or lose their value entirely. You represent and warrant, that you are acquiring VRL Tokens for your own personal use and for your personal utility and not for investment or financial purposes. You also represent and warrant that you do not consider Virtual X as a security and you understand that VRL Tokens may lose all their value and that you are not purchasing VRL Tokens as an investment and that you are aware of all other risks deriving from holding VRL Token as specified in these Terms and you accept them. </li>
            <li>VRL Tokens are unregulated. Virtual X is not a financial institution and is currently not under supervision of any financial supervisory authority. Virtual X does not provide any licensed financial services, such as investment services, fund management or investment advice. None of the information or analysis presented herein are intended to form the basis for any investment decision, no specific recommendations are intended, and Virtual X, website and VRL Tokens do not offer, are not and shall not be construed as investment or financial products. In the event of any regulatory changes would impact the VRL, Virtual X reserves the right to amend its Services, the Website and the VRL Token. </li>
            <li>Token distribution: Token distribution is not a public offering of equity or debt and consequently does not fall under the securities or any prospectus regulation. You can make contribution into a smart contract system in BNB (acceptable Digital Assets) and receive VRL in exchange.</li>
            <li>Knowledge required
              <div>
                <p>10.1. the User purchasing VRL  Tokens expressly acknowledges and represents that she/he has carefully reviewed the T&C and fully understands the risks, costs and benefits associated with the acquisition of this token as indicated in the T&C. </p>
                <p>10.2. the User purchasing VRL  Tokens expressly acknowledges and represents that she/he has carefully reviewed the T&C and fully understands the risks, costs and benefits associated with the acquisition of this token as indicated in the T&C. </p>
                <p>10.3. Virtual X shall not be responsible for any loss of VRL Tokens or situations making it impossible to access to VRL Token, which may result in any actions or omissions of the future User or any person undertaking to acquire VRL  Tokens.</p>
                <p>10.4. Virtual X is not a provider of (a) exchange services between virtual currency and fiat currency; (b) wallet or custodial services of credentials necessary to access virtual currencies or (c) cryptocurrency mining services. User expressly agrees and acknowledges that anytime throughout the duration of these Terms, VRL  Tokens may require material, technical, commercial or any 3 other changes and understands that an upgrade or modification of the VRL  Tokens may be required. If a user decides not to participate in such upgrade, the user acknowledges and agrees that non- upgraded VRL  Tokens may lose their functionality in full and that they may no longer use the VRL  Token.</p>
              </div>
            </li>
            <li className='text-brandColor'>Risks
              <div>
                <p>11.1 Development failure or abortion. Acquiring and storing VRL Tokens involves various risks, in particular that Virtual X may not be able to launch some operations and continue developing its network or community. Therefore, and prior to acquiring VRL, any user should carefully consider the risks, costs, and benefits of acquiring VRL within the Token Sale, and, if necessary, obtain independent advice in this regard. Any interested person who is not in the position to accept nor to understand the risks associated with the activity (incl. the risks related to the non-development of Virtual X network and operations) or any other risks as indicated in the T&C, should not acquire VRL, at this stage or later. </p>
                <p>11.2 Legal Risk concerning Security Regulation. There is a risk that in some jurisdictions VRL  Tokens might be considered as a security, now or in the future. Company does not give warranties or guarantees that VRL Token are not a security in all jurisdictions. Each user of VRL shall bear its own legal or financial consequences of VRL Token being considered a security in their respective jurisdiction. The legal ability of Company to provide VRL Tokens in some jurisdictions may be eliminated by future regulation or legal actions. In the event, it turns out with a high degree of certainty that VRL Tokens are not legal in certain jurisdiction, Company will base on its sole discretion either (a) cease operations in that jurisdiction, or (b) adjust VRL Tokens in a way to comply with the regulation should that be possible and viable. It is your obligation to check if acquisition and disposal of VRL Tokens is legal in your jurisdiction, and by accepting these Terms you expressly agree and warrant that you will not use VRL should their use not be legal in the relevant jurisdiction. </p>
                <p>11.3. Risk of malfunction of blockchain. Nobody can guarantee the source code used by Company will be flaw-free. It may contain certain flaws, errors, defects and bugs, which may disable some functionality for users, expose users’ information or otherwise. Such flaw would compromise the usability and/or security of Company and consequently bring adverse impact on the value of Company open source codes rely on transparency to promote community-sourced identification and solution of problems within the code. </p>
                <p>11.4 Update of the Source Code. The source code could be updated, amended, altered or modified from time to time by the developers and/or the community. Nobody is able to foresee or guarantee the precise result of such update, amendment, alteration or modification. As a result, any update, amendment, alteration or modification could lead to an unexpected or unintended outcome that adversely affects VRL Tokens and/or Company operation or market value. </p>
                <p>11.5. Internet transmission risks. You acknowledge that there are risks associated with utilising an Internet-based digital assets, products and website including, but not limited to, the failure of hardware, software, and Internet connections. You acknowledge that the Company shall not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when using our services, website, network, VRL  Tokens howsoever caused. </p>
                <p>11.6. Cryptography risks. You acknowledge that there are risks associated with cryptography, such as code cracking or technical advances such as the development of quantum computers, could present risks to all crypto-currencies including VRL Tokens. This could result in the theft, loss, disappearance, destruction or devaluation of VRL. To a reasonable extent, Company will be prepared to take proactive or remedial steps to update the protocol underlying Company in response to any advances in cryptography and to incorporate additional reasonable security measures where appropriate. It is impossible to predict the future of cryptography or the future of security innovations to an extent that would permit the Company accurately guide the development of Company to take into account such unforeseeable changes in the domains of cryptography or security. </p>
                <p>11.7 Risk of theft and hacking. Hackers or other groups or organisations may attempt to interfere with your third-party wallet, the Website or the availability of VRL Tokens in any number of ways, including without limitation denial of service attacks, Sybil attacks, spoofing, smurfing, malware attacks, or consensus-based attacks. </p>
                <p>11.8. Risk of mining attacks: BNB Chain, which is used for the VRL Tokens, is susceptible to mining attacks, including but not limited to double-spend attacks, majority mining power attacks,“selfish-mining”attacks, and race condition attacks. Mining Attacks, as described above, may also target other blockchain networks, with which VRL interacts with. Any successful attacks present a risk to the VRL Token. </p>
                <p>11.9 Risk of loss of value and uninsured losses: Value of VRL Tokens may fluctuate and you may suffer loss in value of such acquired VRL Token. In addition to loss of value risk, VRL Tokens are entirely uninsured and are unlike bank accounts or accounts at some other financial institutions. </p>
                <p>11.10 Unanticipated risks: Cryptocurrencies and blockchain technologies are new and untested technology an in addition to the risk outlined in these Terms, there are also unforeseeable risks that may materialise as unanticipated. </p>
                <p>11.11 You acknowledge, agree and warrant that you have been warned of the potential risks involved by using our services, website and product and other relevant technologies mentioned herein as well as that there may be other risks involved, which are not specified herein and that you fully accept such risks. </p>
              </div>
            </li>
            <li className='text-brandColor'>Important Disclaimer:
              <div>
                <p>12.1 The T&C shall not and cannot be considered as an invitation to enter into an investment. They do not constitute or relate in any way nor should they be considered as an offering of securities in any jurisdiction. The T&C do not include or contain any information or indication that might be considered as a recommendation or that might be used to base any investment decision. This document does not constitute an offer or an invitation to sell shares, securities or rights belonging to VRL or any related or associated company. VRL will be used as an entry ticket and is required to qualify for direct access to the VRL  Token when it will be accessible and is not intended to be used as an investment.</p>
                <p>12.2 Any information in the T&C is given for general information purpose only and VRL does not provide with any warranty as to the accuracy and completeness of this information. </p>
                <p>12.3 The offering of VRL Tokens is done in order to allow the utilisation of software services and not for speculative purposes. </p>
                <p>12.4 VRL will be an overseeing entity managing the Virtual X. VRL is not a financial intermediary according to Federation Law and is not required to obtain any authorisation for Anti Money Laundering purpose. </p>
                <p>12.5 Regulatory authorities are carefully scrutinising businesses and operations associated to cryptocurrencies in the world. In that respect, regulatory measures, investigations or actions may affect Virtual X’s business and even limit or prevent it from developing its operations in the future. </p>
                <p>12.6. Any person undertaking to acquire VRL Token must be aware that the VRL business model and the T&C may change or need to be modified because of new regulatory and compliance requirements from any applicable laws in any jurisdictions. In such case, any person undertaking to acquire VRL acknowledge and understand that neither VRL nor any of its affiliates shall be held liable for any direct or indirect loss or damages caused by such changes. </p>
                <p>12.7 Virtual X will do its best to launch its operations and develop the network. Any person undertaking to acquire VRL acknowledges and understands that VRL does not provide any guarantee that it will manage to achieve it. </p>
                <p>12.8. Acquiring VRL shall not grant any right or influence over Virtual X company and governance to the users. These tokens will be issued by a technical process referred to as a «blockchain». This is an open source IT protocol over which the Company has no rights or liability in terms of its development and operation. The token distribution mechanism will be controlled by a Smart Contract; this involves a computer program that can be executed on the Binance Chain or on another «blockchain» network that is compatible with the Smart Contract programming language. User acknowledge and understand therefore that VRL (incl. its bodies and employees) assumes no liability or responsibility for any loss or damage that would result from or relate to the incapacity to use the VRL Token expected in case of intentional misconduct or gross negligence. </p>
                <p>12.9. VRL is based on the Binance protocol. Therefore, any malfunction, unplanned function or unexpected operation of the Binance protocol may cause the VRL Token network to malfunction or operate in a way that is not expected.
                </p>
                <p>12.10 Employees of VirtualX are allowed to operate with VRL Token at market price if they are not in knowledge of information that may modify the price of the Token. </p>
              </div>
            </li>
            <li className='text-brandColor'>Eligibility, Representation and Warranties:
              <div>
                <p>13.1. You must be at least 18 years old to use our services, product and website. By using our services, products and accessing our website you represent and warrant that you: (a) are at least 18 years old; (b) you have full power and authority to enter into this agreement (c) have not been previously suspended or removed from using our services (b) have not been placed on any of the sanctions lists, published and maintained by the United Nations, European Union, any EU country, UK Treasury and US Office of Foreign Assets Control (OFAC); </p>
                <p>13.2. Intellectual Property Rights: To the extent that copyright or other intellectual property rights exist on the VirtualX network, website, VRL Token and services such as software, know-how, analysis or programs, those copyrights and other intellectual and industrial rights belong to VRL. Under no circumstances will these Terms be construed as granting, by implication, estoppel or otherwise, a license to any Intellectual Property or components thereof other than as specifically granted in these terms. You agree that Company’s Intellectual Property may be used only as provided in these terms. All rights not expressly granted herein are reserved. </p>
              </div>
            </li>
            <li className='text-brandColor'>Disclaimer of Warranties:
              <div>
                <p>14.1 To the fullest extent permissible under applicable law, our service, website, VRL TOKENS are provided on an “as is,” and “as available” basis, without warranties of any kind. no warranty of any kind, express, implied or statutory, including implied warranties of condition, uninterrupted use, merchantability, satisfactory quality, fitness for a particular purpose, non-infringement of third party rights, and warranties (if any) arising from a course of dealing, usage, or trade practice, is given in conjunction to website, services, network, VRL TOKEN any software contained in website, VRL TOKEN and services and in general. </p>
                <p>14.2 Company does not warrant that the service, VRL token or website will be error-free or uninterrupted or that any defects will be corrected in reasonable time. you acknowledge that your use of the service, network and website is at your sole risk. </p>
                <p>14.3. While every effort is made to ensure that information contained in the website or VRL is correct, Company disclaims all warranties regarding the accuracy, adequacy, correctness, completeness, reliability, timeliness, non-infringement, title, merchantability or fitness of any information on the Website and/or VRL.</p>
                <p>14.4 Company does not guarantee the confidentiality or privacy of any communication or information transmitted through services, on the Website or VRL or any site linked to the website. We will not be liable for the privacy or security of information, e-mail addresses, registration and any identification information (if applicable), disk space, communications, confidential or proprietary information, or any other content transmitted to us in any manner, or otherwise connected with your use of our services, website or network. </p>
                <p>14.5 Company shall not bear any liability, whatsoever, for any damage or interruptions caused by any computer viruses, spyware, scareware, trojan horses, worms or other malware that may affect your computer or other equipment, or any phishing, spoofing or other attack. We advise the regular use of a reputable and readily available virus screening and prevention software. You should also be aware that email services are vulnerable to spoofing and phishing attacks and should use care in reviewing messages purporting to originate from the Company. Always log into your account through the website to review any transactions or required actions, if you have any uncertainty regarding the authenticity of any communication or notice. </p>
              </div>
            </li>
            <li className='text-brandColor'>Limitation of liability
              <div>
                <p>15.1. Virtual X, as well as its officers, directors, agents, joint ventures, employees, suppliers and advisors, assumes no liability or responsibility for any loss raised from the token sale, arising out of or related to the use of the VirtualX network or any technical, interruption or malfunction of the VirtualX network, website, token, services or otherwise. In no event shall VirtualX, as well as its officers, directors, agents, joint ventures, employees, suppliers and advisors, be liable for any special, indirect, incidental, punitive or consequential damages of any kind whatsoever, including without limitation any damages caused by or resuming from reliance by any user or any information obtained from the Company, or that result from mistakes, omissions, interruptions, deletion of files or email, errors, defects, viruses, delays in operation or transmission or any failure of performance, whether or not resulting from a force majeure event, suspension of Binance Chain communication failure, theft, destruction or unauthorised access to company’s records, services, website, VRL  Token. In addition to the above, company shall not be liable for any loss of profit, loss of business, trading losses, loss in value, or any other loss. This applies even if such damages are foreseeable. </p>
                <p>15.2. The limitation of liability set out above shall not be applicable in the event that VirtualX, or a VirtualX-employee, has caused the damage by intentional misconduct or by gross negligence. </p>
                <p>15.3. each party acknowledges that the fees payable hereunder reflects the allocation of risk set forth in the agreement and that each party would not enter into the agreement without these limitations on liability. </p>
              </div>
            </li>
            <li className='text-brandColor'>Indemnification
              <div>
                <p>16.1 You will defend, indemnify and hold Company, its affiliates and licensors and its officers, directors, contractors, employees, agents and representatives, harmless from and against all claims, actions, demands, liabilities, damages, losses, costs and expenses (including legal fees) relating to or arising from (a) your use of our services, website, network, VRL Token (b) your breach of these terms or any other liabilities arising out of your use of the services, website and product or the use by any other person accessing the website, service, network, VRL  Token using your computer and/or your personal information (c) your violation of any rights of any other person or entity in connection with these terms (d) third-party claims concerning these terms or you thereof. You will promptly notify us of any third-party claims, actions, or proceedings which you become aware of that involves company as a result of these terms. Company may participate with counsel of its own choosing in any proceedings describing above. Company will be required to respond to compulsory legal order, you will reimburse company for reasonable attorney and contractors fees for their time and material spent responding to obligatory legal orders. You will not agree to any settlement which imposes any obligation or liability for company without company’s prior written consent. Links to other Websites</p>
                <p>16.2 Our services, website, network, VRL Token may include links to third party websites, third party wallet providers or other service providers (“Third Party Sites”). If you use any links made available through our services, website, network, application to reach other websites not maintained by the company you will leave our services, website, network, application. The linked sites are not under the control of the company and company is not responsible for the content of 8 any linked site or any link contained in a linked site. The linked sites are governed by the terms and conditions of that site.</p>
                <p>16.3 Company shall not be responsible or liable, either directly or indirectly, for any damage or loss caused or alleged to be caused in connection with your use or reliance on any such content, information, statements, representations, advertising, products, services or other materials available on or through third party sites. Company provides these links to you only as a convenience and the inclusion of any link does not imply recommendation, approval or endorsement by company of third party sites, nor does it imply that the linked third party sites recommends, approves of, or endorses Company. </p>
              </div>
            </li>
            <li className='text-brandColor'>Feedback
              <div>
                <p>In connection with your use of our services, website, network, you may provide us with your feedback (suggestions, ideas, reviews, comments, material and questions or other information and/or material). We will own exclusive rights, including all intellectual property rights, to any feedback, suggestions, ideas or other information or materials you provide to us, whether by email, posting through our services, website, network or otherwise. You waive any rights you may have to the feedback (including any copyrights to the extent permitted by law). And Feedback you provide to us is non- confidential, non-proprietary and is not subject to a third-party license and we have no liability for any loss or damage suffered by you as a result of the disclosure or use of such feedback. We have the right to disclose your identity to any third-party who is claiming that any content posted by you constitutes a violation of their intellectual property rights, or of their right to privacy. We have the right to remove any posting you make on our website if, in our opinion, your post does not comply with the content standards set out in this section. Term and Termination This agreement is entered into for unlimited duration. We reserve the right to terminate and/or suspend your access to our services/website, without giving you prior written notice and delete all related information and files related to your use of our services, website, network, mobile application, without liability to you, at any time for any reason, including, but not limited to, if based on our sole discretion believe: (i) You have violated these Terms, (ii) You create risk or possible legal exposure for us. </p>
              </div>
            </li>
            <li className='text-brandColor'>Notices
              <div>
                <p>18.1. You agree and consent to receive electronically all communications, agreements, documents, receipts, notices and disclosures (collectively, Communications”) that Company provides in connection with your use of Company Services, Website, Network and mobile application. You acknowledge and agree that Company may provide these communications to you by posting them on its Website or by emailing them to you at the email address you provide. Any email communication will be considered to be received by you within 24 hours after we email it to you and Communication via our Website will be effective upon posting. You should maintain copies of electronic Communications by printing a paper copy or saving an electronic copy. </p>
                <p>18.2. It is your responsibility to keep your email address with the Company up to date so that the Company can communicate with you electronically. You understand and agree that if the Company sends you an electronic communication but you do not receive it because your email address is incorrect, out of date, blocked by your service provider, or you are otherwise unable to receive electronic communications, Company will be deemed to have provided the communication to you. Please note that if you use a spam filter that blocks or re-routes emails from senders not listed in your email address book, you must add the Company to your email address book so that you will be able to receive the communications we send to you. </p>
              </div>
            </li>
            <li className='text-brandColor'>Taxes
              <div>
                <p>19.1. You are solely responsible and liable to declare, bear and pay all taxes, duties, imposts, levies, tariffs and surcharges that might be imposed by the laws and regulations of any jurisdiction as a result of or in connection with the use of services, website, network, VRL Token or any other Company product. Company is not giving any advice regarding tax issues and is not responsible for determining any tax implications connected with its Services, Website, Network, and the VRL  Token. Company makes no representation as to the tax implication of any jurisdiction. You shall be solely liable for all such penalties, claims, fines, punishments, liabilities or otherwise arising from his/her underpayment, undue payment or belated payment of any applicable tax. </p>
                <p>19.2. All fees and charges payable by you to Company are exclusive of any taxes and if certain taxes shall be applicable, they shall be added on top of applicable amount. Upon our request, you will provide us any information we reasonably request to determine whether we are obligated to collect VAT from you, including your VAT identification number. If any deduction or withholding is required by law, you will notify us and will pay us any additional amounts necessary to ensure that the net amount that we receive, after any deduction and withholding, equals the amount we would have received if no deduction or withholding had been required. Additionally, you will provide us with documentation showing that the withheld and deducted amounts have been paid to the relevant taxing authority. </p>
              </div>
            </li>
            <li className='text-brandColor'>Usage and sharing
              <p>We use personal information to provide our services and products, for administering our business activities, to communicate with you, to promote safety and security (we use personal information for loss prevention, anti- fraud and/or unauthorised activity and to enforce these terms) and to provide you with customer service, technical support, for audit purposes, to prevent and investigate potentially prohibited or illegal activates and to notify you about improvements to our website and new services we think you will find useful. We can use personal information so as to mitigate the risk of fraud, identity theft or credit card theft. We may use your name and email address to provide you with information about products or services that may be of interest to you. </p>
            </li>
            <li className='text-brandColor'>Sharing of personal data.
              <p>We take your privacy very seriously, and will only share your personal information as needed with the entities within the ecosystem to perform the services and in the event if we are legally to meet any legal, regulatory, or governmental request, including but not limited to events when we are compelled to do so by a subpoena, court order, or similar legal procedure; Miscellaneous </p>
            </li>
            <li className='text-brandColor'>Entire Agreement
              <div>
                <p>22.1. These terms represent the entire agreement, and supersede all prior and contemporaneous understandings between you and the Company regarding the subject matter, especially regarding the services, website, network and VRL  Token. In the event of any conflict between these terms and any other agreement you may have with the Company, the terms of that other agreement will prevail only if these terms are specifically identified and declared to be overridden by such other agreement. </p>
                <p>22.2. Assignment. These Term shall be binding upon and inure to the benefit of the parties and their permitted successors and assigns. You may not assign or transfer any of your rights or obligations under these Terms without Company’s prior written consent from, including by operation of law or in connection with any change of control. Company may assign or transfer any or all of its rights under these Terms, in whole or in part, without obtaining your prior written consent or approval. </p>
                <p>22.3.  Act of God Events. Company shall not be liable for (1) any inaccuracy, error, delays or omission of (i) any information, or (ii) the transmission or delivery of information; (2) any loss or damage arising from flood, extraordinary weather conditions, earthquake, or other act of God, fire, war, insurrection, riot, labor dispute, accident, action of government, communications, power failure, or equipment or software malfunction or any other cause beyond Company’s reasonable control (each, aka“Force Majeure Event”). </p>
                <p>22.4. Waiver. Company failure or delay in exercising any right, power or privilege under these Terms shall not operate as a waiver thereof.</p>
              </div>
            </li>
          </ol>
        </div>
      </main>
    </>
  );
};

export default Terms;